---
name: Ko

on: [push, pull_request, create]  # create is for tags

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
          version: latest
          args: --timeout=5m

    - name: Controller Gen
      run: make tools/bin/controller-gen

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Publish Image
      uses: imjasonh/setup-ko@v0.6
      with:
        version: v0.11.2
        
    - run: ko build
